configs = {
        "picorv32_basicmath":{
            "python_cmd":"python3",
            "design_folder":"picorv32/benchmark_basicmath",
            "top_module_name":"picorv32",
            "tb_clk":"clk",
            "tb_rst":"rst",
            "top_hier":"top.uut",
            "min_cyc":5,
            "max_cyc":2675
        },
        "picorv32_firmware":{
            "python_cmd":"python3",
            "design_folder":"picorv32/benchmark_firmware",
            "top_module_name":"picorv32_axi",
            "tb_clk":"clk",
            "tb_rst":"rst",
            "top_hier":"top.uut",
            "min_cyc":5,
            "max_cyc":388059
        },
        "picorv32_dhrystone":{
            "python_cmd":"python3",
            "design_folder":"picorv32/benchmark_dhrystone",
            "top_module_name":"picorv32",
            "tb_clk":"clk",
            "tb_rst":"resetn",
            "top_hier":"top.uut",
            "min_cyc":5,
            "max_cyc":19112
        },
        "sha1":{
            "python_cmd":"python3",
            "design_folder":"sha1",
            "top_module_name":"sha1_core",
            "tb_clk":"tb_clk",
            "tb_rst":"tb_reset_n",
            "top_hier":"tb_sha1_core.dut",
            "min_cyc":5,
            "max_cyc":244
        },
        "FFTx32":{
            "python_cmd":"python3",
            "design_folder":"FFTx32/src",
            "top_module_name":"FFT",
            "tb_clk":"clk",
            "tb_rst":"rst_n",
            "top_hier":"FFT_CORE",
            "min_cyc":5,
            "max_cyc":80
        },
        "vSPI":{
            "python_cmd":"python3",
            "design_folder":"vSPI",
            "top_module_name":"spiifc",
            "tb_clk":"SysClk",
            "tb_rst":"Reset",
            "top_hier":"spiifc_tb2.uut",
            "min_cyc":5,
            "max_cyc":225
        },
        "tinyriscv":{
            "python_cmd":"python3",
            "design_folder":"tinyriscv",
            "top_module_name":"tinyriscv",
            "tb_clk":"clk",
            "tb_rst":"rst",
            "top_hier":"tinyriscv_soc_tb.tinyriscv_soc_top_0.u_tinyriscv",
            "min_cyc":5,
            "max_cyc":10000
        }
    }
