configs = {
        "picorv32_basicmath":{
            "python_cmd":"python3",
            "design_folder":"picorv32/benchmark_basicmath",
            "top_module_name":"picorv32",
            "tb_clk":"clk",
            "tb_rst":"rst",
            "top_hier":"top.uut",
            "min_cyc":5,
            "max_cyc":1028
        },
        "picorv32_firmware":{
            "python_cmd":"python3",
            "design_folder":"picorv32/benchmark_firmware",
            "top_module_name":"picorv32_axi",
            "tb_clk":"clk",
            "tb_rst":"rst",
            "top_hier":"top.uut",
            "min_cyc":5,
            "max_cyc":1028
        },
        "picorv32_dhrystone":{
            "python_cmd":"python3",
            "design_folder":"picorv32/benchmark_dhrystone",
            "top_module_name":"picorv32",
            "tb_clk":"clk",
            "tb_rst":"rst",
            "top_hier":"top.uut",
            "min_cyc":5,
            "max_cyc":1028
        },
        "tinyriscv":{
            "python_cmd":"python3",
            "design_folder":"picorv32/benchmark_basicmath",
            "top_module_name":"picorv32",
            "tb_clk":"clk",
            "tb_rst":"rst",
            "top_hier":"top.uut",
            "min_cyc":0,
            "max_cyc":5
        }
    }
